#!/bin/bash
set -e -u -o pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> <eeg data file name> <channel location file name>

    description
eof
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

subject_number="$1"

mkdir "$subject_number" || true

log_file="$subject_number/$(date +%s).log"

echo "preprocessing eeg data for $subject_number, writing to log file $log_file" >&2
matlab \
    -nodisplay \
    -r \
    "preprocess_eeg_data('$subject_number','${subject_number}_eeg_data.raw','${subject_number}_channel_locations.sfp')" \
    &> "$log_file" &

# bash wizardry
matlab_pid="$!"
echo "to kill it, run $ kill $matlab_pid" >&2

# don't kill the process if this terminal exits
disown
