#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

# Retrieve output data files and extract
ssh cronusx "cd tcdp ; tar cJvf tfce_output.tar.xz 5_cluster_cross_correlations/data/cluster_scores 5_cluster_cross_correlations/data/logs"
scp cronusx:tcdp/tfce_output.tar.xz .
tar xJvf tfce_output.tar.xz

# Plot permutations
./5_cluster_cross_correlations/scripts/run-plot-permutations
