#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

for condition in overall S T M N L H talker meaning constraint; do
    Rscript --vanilla 5_cluster_cross_correlations/src/plot_permutations.R "$condition"
done
