#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

for condition in overall S T M N L H talker meaning constraint; do
#for condition in SL SH TL TH ML MH NL NH; do
    ./5_cluster_cross_correlations/src/get_weight_scores.R "$condition"
done

printf "weight scores created"
