#!/bin/bash

set -euo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

Rscript --vanilla 5_cluster_cross_correlations/src/get_distance_scores.R

printf "distance_scores.RDS created in data/distance_scores"
