#!/bin/bash
#PBS -N talker_normalization_permutations
#PBS -l walltime=0:02:00
#PBS -l nodes=1:ppn=1,mem=2gb
#PBS -e perms.err
#PBS -o perms.out
#PBS -m abe

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <condition e.g. S, T, talker>" >&2
    exit 1
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

condition="$1"

log_file="5_cluster_cross_correlations/data/logs/${condition}_${job_id}.log"
echo "$log_file"

Rscript --vanilla 5_cluster_cross_correlations/src/permutations.R "$condition" 2>&1 \
    | tee -a "$log_file"

printf "\n\n permutation complete \n\n"
