#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        wrapper script for cross_correlate.m
        loops over data from all subjects
        cross correlates eeg signal from each epoch
        and each channel with its corresponding auditory stimuli
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

while read -r subject_number; do
    matlab -nodisplay -r "addpath('2_cross_correlate/src'); get_split_conditions('$GIT_HOME'); quit"
done < 0_set_up_and_raw_data/data/subject_numbers.txt
