#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <maximum, lag, or abs_average>

    description
        wrapper script for combining xcorr values from all 
        subjects into one file
eof
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

stat="$1"

matlab -nodisplay -r "addpath('2_cross_correlate/src'); concat_xcorr('$GIT_HOME', '$stat')"
