#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

for condition in overall S T M N L H talker meaning constraint; do
    ./threshold_free_clustering/src/get_weight_scores.R "$condition"
done

printf "weight scores created"
