#!/bin/bash

set -euo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

Rscript --vanilla threshold_free_clustering/src/get_distance_scores.R
Rscript --vanilla threshold_free_clustering/src/get_weight_scores.R

printf "distance_scores.RDS created in data/distance_scores"
printf "weight scores ('S.RDS', 'T.RDS', 'talker.RDS'...) created in data/weight_scores"
