#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <multilevel/simple_linear>"
    exit 1
fi

cd "$(git rev-parse --show-toplevel)"

model_type="$1"

Rscript --verbose src/5_rms/compile_model_stats.R $model_type

