#!/bin/bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <start_channel> <end_channel>" >&2
    exit 1
fi

cd "$(git rev-parse --show-toplevel)"

start_channel="$1"
end_channel="$2"

Rscript --verbose 5_rms/src/generate_meaning_models.R $start_channel $end_channel

