#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        wrapper script for combining xcorr values from all 
        subjects into one file
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

matlab -nodisplay -r "addpath('5_rms/src'); get_xcorr_for_all_subjects('$GIT_HOME')"
