#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <fstem, e.g. average, max, or coherence for full>

    description
        wrapper script for combining coherence values from 
        all subjects into one file
eof
    exit 1
}

fstem="$1"

if [[ $# -ne 1 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

matlab -nodisplay -r "addpath('6_coherence/src'); concat_coherence('$GIT_HOME', '$fstem')"
