---
title: "Maximum cross correlation plots"
output: html_notebook
---

```{r setup, warning=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_knit$set(root.dir = "/Users/letitiaho/src/talker_change_data_processing/")
setwd("/Users/letitiaho/src/talker_change_data_processing/")
library("dplyr")
library("ggplot2")
library("ggpubr")
library("kableExtra")
source("tools/functions.R")
source("4_test_cross_correlations/src/functions.R")
```

### Set up

```{r}
load("4_test_cross_correlations/data/wilcoxon_against_overall.RData")
```

```{r}
# Commonly used vars
coordinates <- get_layout()
channels <- as.character(c(1:128))
```

```{r}
# Functions
get_inverted_list <- function(channels, list) {
  inverted_list <- channels[!channels %in% list] %>%
    as.numeric()
  return(inverted_list)
}

get_relevant_coords <- function(x, y, channels) {
  x <- x[channels]
  y <- y[channels]
  return(data.frame(x = x, y = y))
}

get_map <- function(df, channels, nodiff_channels, levels_label) {
  diff_coordinates <- get_relevant_coords(df$x, df$y, channels)
  nodiff_coordinates <- get_relevant_coords(df$x, df$y, nodiff_channels)

  ggplot() +
    geom_point(data = df, aes(x = x, y = y,
                              size = 1/group1,
                              color = "1",
                              alpha = 0.85,
                              stroke = 1)) +
    geom_point(data = df, aes(x = x, y = y,
                              size = 1/group2,
                              color = "2",
                              alpha = 0.85,
                              stroke = 1)) +
    geom_point(data = df, aes(x = 1000+x, y = y,
                              size = 1/nodiff_group1,
                              color = "1",
                              alpha = 0.85,
                              stroke = 1)) +
    geom_point(data = df, aes(x = 1000+x, y = y,
                              size = 1/nodiff_group2,
                              color = "2",
                              alpha = 0.85,
                              stroke = 1)) +
    scale_color_discrete(name = "Level", labels = levels_label) +
    scale_size_continuous(name = "p",
                          range = c(0, 20),
                          limits = c(1, 200),
                          breaks = c(20, 100, 200),
                          labels = c("0.05", "0.01", "0.005")) +
    guides(alpha = FALSE) +
    annotate("text", x=20, y=5, label= "L", alpha = 0.8) +
    annotate("text", x=880, y=5, label= "R", alpha = 0.8) +
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank())
}

recode_ps <- function(ps, channels){
  recoded_ps <- c()
  for (i in 1:128) {
    # Get p-value for channel i
    p <- ps[i]

    # Exit early if not in list of significant channels
    if (!(i %in% channels)) {recoded_ps[i] = NaN}

    # Recoding values if too small or too large
    else {
      if (p < 0.005) {p <- 0.005}
      recoded_ps[i] <- p
    }
  }
  return(recoded_ps)
}
```

## Talker

*Tracking for same-talker condition compared to baseline*

```{r}
# Identify channels that differentiate between same and different talker and channels that don't
talker_channels <- get_sig_channels(talker_w$p)
nodiff_talker_channels <- get_inverted_list(channels, talker_channels)

# Get p-values for tracking within each level
greater_S <- recode_ps(S_w_mu_greater$p, talker_channels)
less_S <- recode_ps(S_w_mu_less$p, talker_channels)
nodiff_greater_S <- recode_ps(S_w_mu_greater$p, nodiff_talker_channels)
nodiff_less_S <- recode_ps(S_w_mu_less$p, nodiff_talker_channels)

# Create data frame for bubbles
talker_df <- data.frame(group1 = greater_S, group2 = less_S, nodiff_group1 = nodiff_greater_S, nodiff_group2 = nodiff_less_S, coordinates)

# Plot
plot <- get_map(talker_df, talker_channels, nodiff_talker_channels, c("Greater tracking", "Less tracking"))
plot
fname = paste('4_test_cross_correlations/figs/max_S.png', sep = "")
ggsave(plot = plot, filename = fname, width = 12, height = 5)
```

*Tracking for different-talker condition compared to baseline*

```{r}
# Get p-values for tracking within each level
greater_T <- recode_ps(T_w_mu_greater$p, talker_channels)
less_T <- recode_ps(T_w_mu_less$p, talker_channels)
nodiff_greater_T <- recode_ps(T_w_mu_greater$p, nodiff_talker_channels)
nodiff_less_T <- recode_ps(T_w_mu_less$p, nodiff_talker_channels)

# Create data frame for bubbles
talker_df <- data.frame(group1 = greater_T, group2 = less_T, nodiff_group1 = nodiff_greater_T, nodiff_group2 = nodiff_less_T, coordinates)

# Plot
plot <- get_map(talker_df, talker_channels, nodiff_talker_channels, c("Greater tracking", "Less tracking"))
plot
fname = paste('4_test_cross_correlations/figs/max_T.png', sep = "")
ggsave(plot = plot, filename = fname, width = 12, height = 5)
```
### Barplots

```{r}
# Average across all channels
xcorr <- read.csv(file = "3_cross_correlate/data/maximum.csv")
channel_columns = paste("X", as.character(1:128), sep = "")

# Compute baseline
overall <- get_subject_averages(xcorr)
baseline <- apply(overall, 2, mean) %>%
  rep(11) %>%
  matrix(nrow = 11, byrow = TRUE) # Cast it so baseline is the same shape as the condition cross correlation matrices

# Subset each condition
S <- subset(xcorr, talker = "S") %>% get_subject_averages()
T <- subset(xcorr, talker = "T") %>% get_subject_averages()
M <- subset(xcorr, meaning = "M") %>% get_subject_averages()
N <- subset(xcorr, meaning = "N") %>% get_subject_averages()
L <- subset(xcorr, constraint = "L") %>% get_subject_averages()
H <- subset(xcorr, constraint = "H") %>% get_subject_averages()

# Take baseline
S_baselined <- S-baseline
T_baselined <- T-baseline
M_baselined <- M-baseline
N_baselined <- N-baseline
L_baselined <- L-baseline
H_baselined <- H-baseline

# Average across channels 
S_averaged <- S_baselined %>% rowMeans()
T_averaged <- T_baselined %>% rowMeans()
M_averaged <- M_baselined %>% rowMeans()
N_averaged <- N_baselined %>% rowMeans()
L_averaged <- L_baselined %>% rowMeans()
H_averaged <- H_baselined %>% rowMeans()

print(S_averaged)
hist(S_averaged)
```

```{r}
# df <- data.frame(cond = rep('S', length(talker_counts)), counts = talker_counts) %>%
#   rbind(data.frame(cond = rep('T', length(meaning_counts)), counts = meaning_counts)) %>%
#   rbind(data.frame(cond = rep('constraint', length(constraint_counts)), counts = constraint_counts))

max_cond <- data.frame(cond = rep('same', length(S_averaged)), r = S_averaged) %>%
  rbind(data.frame(cond = rep('different', length(T_averaged)), r = T_averaged)) %>%
  rbind(data.frame(cond = rep('meaningful', length(M_averaged)), r = M_averaged)) %>%
  rbind(data.frame(cond = rep('nonsense', length(N_averaged)), r = N_averaged)) %>%
  rbind(data.frame(cond = rep('low', length(L_averaged)), r = L_averaged)) %>%
  rbind(data.frame(cond = rep('high', length(H_averaged)), r = H_averaged))
max_cond$cond <- factor(max_cond$cond , levels=c("same", "different", "meaningful", "nonsense", "low", "high"))

ggplot(max_cond, aes(x = cond, y = r)) +
  scale_fill_brewer(palette="Blues") +
  geom_signif(comparisons = list(c("different" , "same")), map_signif_level = TRUE) +
  geom_boxplot()
  # ylim(22, 35)
```


