#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        wrapper script for baseline_correct.m
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

while read -r subject_number; do
    matlab -nodisplay -r "addpath('9_N1_RMS/src'); cross_correlate('$GIT_HOME'); quit"
done
