#!/bin/bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# loop over each files that we're passed
for f in 0_set_up_and_raw_data/data/*/stim_order.txt; do
    tmp_f="$f.tmp"
    head -1 "$f" \
        | cut -f3,6 \
        | column -t \
        | tee "$tmp_f"
    cat "$f" \
        | sed '1d' \
        | cut -f3,6 \
        | column -t \
        | grep -v ^single \
        | grep -v ^what \
        | grep -v ^..W \
        | sort -k1.1,1.3 -s \
        | tee -a "$tmp_f"
    mv "$tmp_f" "$f"
done

echo "done :^)" >&2
