---
title: "Generate models"
author: "Letitia Ho"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  start_channel: 0
  end_channel: 128
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/letitiaho/src/talker_change_data_processing")
library(dplyr)
library(ggplot2)
library(rethinking)
theme_set(theme_minimal())  
```

```{r load_data, include=FALSE}
source("src/5_rms/functions.R")
xcorr <- read.csv('data/5_rms/maximum.csv')
rms <- read.csv('data/5_rms/rms.csv')
```

**Average over rms for left and right superior parietal**

```{r}
left_superior_parietal <- data.frame(rms$epoch_rms53, rms$epoch_rms54, rms$epoch_rms60, rms$epoch_rms61, rms$epoch_rms67) %>%
  rowMeans()
right_superior_parietal <- data.frame(rms$epoch_rms77, rms$epoch_rms78, rms$epoch_rms79, rms$epoch_rms85, rms$epoch_rms86) %>%
  rowMeans()
```

###Generate models and figures for channels in the specified range

```{r}
for (channel_number in params$start_channel:params$end_channel) {
  model <- get_model_for_one_channel(left_superior_parietal, xcorr, channel_number)
}
```




