#!/bin/bash

set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    Downsamples audio to 1000 hz and filters around f0 of talker
eof
    exit 1
}

GIT_HOME="$(git rev-parse --show-toplevel)"
echo "Working from $GIT_HOME"
cd "$GIT_HOME"

for f in 0_set_up_and_raw_data/data/stim/original/*.wav; do
    if [[ $f == *"_preprocessed"* ]]; then
        echo "skipping $f"
        continue
    elif [[ $f == *"_f.wav" ]]; then
        high_pass=130
        low_pass=320
    elif [[ $f == "word_"* ]]; then
        high_pass=60
        low_pass=250
    fi

    base="$(basename "$f")"
    preprocessed_f="3_cross_correlate/data/stim/$base"
    echo "Filtering $f to $preprocessed_f"

    downsample=1000
    sox "$f" -r "$downsample" "$preprocessed_f" highpass "$high_pass" lowpass "$low_pass"
done

echo "done :^)"
