#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <file stem, e.g. 'lag_normalized', 'average_below_f0_normalized'>

    description
        wrapper script for combining xcorr values from all 
        subjects into one file
eof
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

fstem="$1"

matlab -nodisplay -r "addpath('3_cross_correlate/src'); concat_xcorr('$GIT_HOME', '$fstem')"
