#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> ...

    description
        wrapper script for convolve_and_cross_correlate.m
        convolve and cross correlate eeg signal from each epoch
        and each channel with its corresponding auditory stimuli
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

while read -r subject_number; do
    matlab -nodisplay -r "addpath('src/5_rms'); get_rms('$GIT_HOME', '$subject_number')"
done < ./scripts/subject_numbers.txt
