#!/bin/bash
#PBS -N talker_normalization_permutations
#PBS -l walltime=0:02:00
#PBS -l nodes=1:ppn=1,mem=2gb
#PBS -e perms.err
#PBS -o perms.out
#PBS -m abe

set -exuo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <condition e.g. S, T, talker> <job_id>" >&2
    exit 1
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

condition="$1"
job_id="$2"

echo $condition
echo $job_id
log_file="./7_cluster_coherence/data/logs/${condition}_${job_id}.log"
echo "$log_file"

Rscript --vanilla threshold_free_clustering_coherence/src/permutations.R "$condition" 2>&1 \
    | tee -a "$log_file"

printf "\n\n permutation complete \n\n"
