#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

job_id=$(date +%s)

for condition in overall S T M N L H; do
    ./7_cluster_coherence/scripts/run-permutations-for-one-condition \
        "$condition" \
        "$job_id" \
        &> ./7_cluster_coherence/data/logs/master_"$job_id".log \
        &
done
