#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

job_id=$(date +%s)

#for condition in overall S T M N L H talker meaning constraint; do
#for condition in SL SH TL SH ML MH NL NH; do
for condition in S T M N L H; do
    ./threshold_free_clustering_coherence/scripts/run-permutations-for-one-condition \
        "$condition" \
	"$job_id" \
        &> ./threshold_free_clustering_coherence/data/logs/master_"$job_id".log \
        &
done
