#!/bin/bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

if [ ! -r .env ]; then
    echo "Missing '.env' file!  Creating one now.  You need to specify a FILE_INSTALLATION_KEY and try again" >&2
    cp ./.env.template ./.env
    exit 1
fi

source .env

sed "s/FILE_INSTALLATION_KEY/$FILE_INSTALLATION_KEY/g" ./installer_input.txt.template > ./installer_input.txt

echo "Not implemented!"
exit 1
