#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        Runs cross correlations and then runs the script to shape the cross correlations
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME = "$(git rev-parse --show-toplevel)"
cd "GIT_HOME"

log_file="data/logs/$(date +%s).log"

while read -r subject_number; do
    matlab -nodisplay -r "addpath('src'); cross_correlate('$GIT_HOME', '$subject_number')" 2>&1 \
    | tee -a "$log_file"
done < ./scripts/subject_numbers.txt

matlab -nodisplay -r "addpath('src'); shape_data('$GIT_HOME', '$subject_number')" 2>&1 \
    | tee -a "$log_file"

tar czvf archive.tar.gz data/aggregate/*.csv
