#!/bin/bash
set -e -u -o pipefail

usage() {
    cat <<eof >&2
usage: $0 <band> <subject number> ...

    description
        specify the eeg band you want to extract from the data
        options are 'delta' (1-4), 'theta' (4-8), 'alpha' (8-14), 
        'beta1' (14-20), 'beta2' (20-30), 'gamma1' (30-50), 
        'gamma2' (50-100 Hz). then list the subjects whose data
        you want to preprocess 
        (e.g. ./scripts/preprocess-eeg-data-with-bands delta 302)
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

cd "$(git rev-parse --show-toplevel)"

band="$1"

shift

while read -r subject_number; do
    # create a log file
    log_file="data/$subject_number/$(date +%s).log"

    # preprocess the data
    echo "preprocessing eeg data for $subject_number, writing to log file $log_file" >&2
    matlab -nodisplay -r "addpath('src'); preprocess_eeg_data_with_bands('$subject_number', '$band')" 2>&1 \
        | tee "$log_file"
    echo "done >:)"
done < ./scripts/subject_numbers.txt
