#!/bin/bash
set -e -u -o pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> ...

    description
eof
    exit 1
}

if [[ $# -eq 0 ]]; then
    usage
fi

cd "$(git rev-parse --show-toplevel)"

#subject_number="$1"

while read -r subject_number; do
    # create a log file
    log_file="data/$subject_number/$(date +%s).log"

    # preprocess the data
    echo "preprocessing eeg data for $subject_number, writing to log file $log_file" >&2
    matlab -nodisplay -r "addpath('src'); preprocess_eeg_data('$subject_number')" 2>&1 \
        | tee "$log_file"
    echo "done >:)"
done < subject_numbers.txt
