#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> ...

    description
        wrapper script for convolve_and_cross_correlate.m
        convolve and cross correlate eeg signal from each epoch
        and each channel with its corresponding auditory stimuli
eof
    exit 1
}

if [[ $# == 0 ]]; then
    usage
fi

cd "$(git rev-parse --show-toplevel)"

for subject_number in  "$@"; do
    matlab -nodisplay -r "addpath('src'); convolve_and_cross_correlate_with_formants('$subject_number')"
done
