#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0

    description
        wrapper script for cross_correlate.m
        loops over data from all subjects
        cross correlates eeg signal from each epoch
        and each channel with its corresponding auditory stimuli
eof
    exit 1
}

if [[ $# -ne 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

log_file="data/tmp/$(date +%s).log"

while read -r subject_number; do
    matlab -nodisplay -r "addpath('src'); cross_correlate('$GIT_HOME', '$subject_number')" 2>&1 \
        | tee -a "$log_file"
done < ./scripts/subject_numbers.txt
