#!/bin/bash
set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> ...

    description
        wrapper script for cross_correlate.m
        cross correlates eeg signal from each epoch
        and each channel with its corresponding auditory stimuli
eof
    exit 1
}

if [[ $# == 0 ]]; then
    usage
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME"

for subject_number in  "$@"; do
    matlab -nodisplay -r "addpath('src'); cross_correlate('$GIT_HOME', '$subject_number')"
done
