#!/bin/bash
set -euo pipefail

#Usage
usage() {
    cat <<eof >&2
usage: $0 <number of scrambles>

    description
        Runs cross correlations with resampled eeg and audio pairings and then runs the script to shape the cross correlations
eof
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi


# Bind vars
cd tcdp
GIT_HOME="$(git rev-parse --show-toplevel)"
scrambles="$1"
timestamp="$(date +%s)"
log_file="data/logs/${SLURM_JOB_ID}_$timestamp.log"
output_file="data/aggregate/${SLURM_JOB_ID}_$timestamp"

# Load modules
set +euo pipefail
module load matlab/2019b
set -euo pipefail

# Run permutation test
matlab -nodisplay -r "addpath('src'); scramble('$GIT_HOME', '$scrambles', '$output_file'); quit" 2>&1 \
    | tee -a "$log_file"

printf "\n\n Permutation tests complete \n\n"
