#!/bin/bash

set -o errexit -o nounset -o pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> <channel> <epoch> <bin center (Hz)>
eof
    exit
}

if [[ $# -ne 4 ]]; then
    usage
fi

subject="$1"
channel="$2"
epoch="$3"
bin_center="$4"

ssh lettuce <<EOF
#!/bin/bash --login
cd /home/ubuntu/talker_change_data_processing/src/archive
/usr/local/matlab/bin/matlab -nodisplay -nodesktop -nosplash -r "test_filter('$subject', '$channel', '$epoch', '$bin_center'); exit"
EOF

scp "lettuce:talker_change_data_processing/src/archive/test_filter_$subject$channel$epoch.png" .
xdg-open "test_filter_$subject$channel$epoch.png"
