---
title: "Talker change data processing"
author: "Letitia Ho"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
require("knitr")
library("dplyr")
library("kableExtra")
library("ggplot2")
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE
) 
```

```{r fns_load_and_subset_data}
get_layout <- function() { 
  fp <- "/Applications/eeglab2019/talker-change-data-processing/data/aggregate/electrode_points"
  coordinates <- read.delim(fp, header = FALSE)
  layout <- data.frame(x = coordinates[[1]], y = -coordinates[[2]]+ 2*mean(coordinates[[2]])) # flip y coords
  return(layout)
}

# get_contains_area <- function(areas) {
#   contains = c()
#   for (i in 1:128) {
#     temporal <- sum(grep('Temporal', areas[[i]]))
#     frontal <- sum(grep('Frontal', areas[[i]]))
#     if (temporal > 0) {contains[i] <- 'Temporal'}
#     if (frontal > 0) {contains[i] <- 'Frontal'}
#     if (temporal > 0 & frontal > 0) {contains[i] <- 'Both'}
#     if (temporal == 0 & frontal == 0) {contains[i] <- 'None'}
#   }
#   return(contains)
# }

get_combined_central <- function(aal) {
  for (i in 1:length(aal)) {
    indexes <- grep('central', aal[[i]])
    aal[[i]][indexes] <- 'Central'
  }
  return(aal)
}

get_main_areas <- function(aal) {
  # Init a matrix to store tallies of areas labeled
  areas = c("Temporal", "Frontal", "Occipital", "Supp", "Central", "SupraMarginal", "Angular", "Parietal")
  tallies = matrix(0, 128, 8) 
  colnames(tallies) <- areas
  
  # Tally
  for (i in 1:length(aal)) {
    for (j in 1:length(aal[[i]])) {
      main_area <- sub("\\_.*", "", aal[[i]][j])
      # aal[[i]][j] <- ifelse(main_area %in% areas, main_area, "Other")
      tallies[i, grep(main_area, areas)] <- tallies[i, grep(main_area, areas)] + 1
    }
  }
  return(as.data.frame(tallies))
}
```

```{r import}
load("/Applications/eeglab2019/talker-change-data-processing/data/aggregate/mni_coordinates_areas_aal.Rdata")
layout <- get_layout()
```

```{r identify main cortical areas}
aal_cleaned <- get_combined_central(aal)
aal_reduced <- get_main_areas(aal_cleaned)
df <- cbind(layout, aal_reduced)



# # Create a custom color scale
# myColors <- c("#fc9d03", "#coloffd91c", "#a0a0a0", "#fc8003")
# names(myColors) <- levels(df$groups)
# channels <- as.character(1:128)
# 
# ggplot() +
#   geom_point(data = df, aes(x = x, y = y, color = major_regions, size = 7)) +
#   geom_text(data = df, aes(x = x, y = y, label = channels), vjust = -1) +
#   scale_color_manual(name = "Region", values = myColors) + 
#   ylim(0, 900) +
#   xlim(0, 900) +
#   theme(axis.line=element_blank(),axis.text.x=element_blank(),
#         axis.text.y=element_blank(),axis.ticks=element_blank(),
#         axis.title.x=element_blank(),
#         axis.title.y=element_blank(),
#         panel.background=element_blank(),
#         panel.border=element_blank(),
#         panel.grid.major=element_blank(),
#         panel.grid.minor=element_blank(),
#         plot.background=element_blank())


# all_areas <- unique(sub("\\_.*", "", unlist(aal)))


```

