---
title: "Talker change data processing"
author: "Letitia Ho"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
require("knitr")
library("dplyr")
library("kableExtra")
library("ggplot2")
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE
) 
```

```{r fns_load_and_subset_data}
# Load data
load_data <- function(method, formants = FALSE) {
  if (method == "xcorr") {
    if (formants)
      return(read.csv("data/aggregate/cross_correlation_formant_data.csv"))
    return(read.csv("data/aggregate/cross_correlation_data.csv"))
  }
  if (method == "conv") {
    if (formants)
      return(read.csv("data/aggregate/convolution_formant_data.csv"))
    return(read.csv("data/aggregate/convolution_data.csv"))
  }
  stop("Invalid method, options are \"xcorr\" or \"conv\"")
}

# Function for subsetting data based on condition and level
subset <- function(data, formants = NaN, condition, level) {
  channel_columns = paste("X", 1:128, sep = "")
  
  # Subset by formant if specified
  if (formants == "f0") {
    data <- filter(data, formant == "f0")
  } else if (formants == "f1_f2") {
    data <- filter(data, formant == "f1_f2") 
  } else if (formants == "f3") {
    data <- filter(data, formant == "f3")
  }
  
  # Subset by condition if specified
  if (condition == "talker") {
    if (level == "S")
      return(filter(data, talker == "S") %>% select(all_of(channel_columns)))
    return(filter(data, talker == "T") %>% select(all_of(channel_columns)))
  } else if (condition == "meaning") {
    if (level == "M")
      return(filter(data, meaning == "M") %>% select(all_of(channel_columns)))
    return(filter(data, meaning == "N") %>% select(all_of(channel_columns)))
  } else if (condition == "constraint") {
    if (level == "S")
      return(filter(data, constraint == "S") %>% select(all_of(channel_columns)))
    return(filter(data, constraint == "G") %>% select(all_of(channel_columns)))
  }
}
```

```{r fns_statistical_tests}
# Function for running a one-sample t-test and saving the p-value, t-statistic, and df
get_one_sample_t <- function(data) {
  t <- apply(data, MARGIN = 2, function(channel) {t.test(channel)$statistic})
  return(t)
}

# Function for running a paired-samples t-test and saving the p-value, t-statistic, and df
get_paired_samples_t <- function(group1, group2) {
  t <- mapply(function(x, y) {t.test(x, y, paired = TRUE)$statistic}, group1, group2)
  return(t)
  }
```

```{r plotting}
get_layout <- function() { 
  fp <- "/Applications/eeglab2019/talker-change-data-processing/data/aggregate/electrode_points"
  coordinates <- read.delim(fp, header = FALSE)
  x <- coordinates[[1]]
  y <- -coordinates[[2]]+ 2*mean(coordinates[[2]]) # flip y coords and return to original center
  return(list(x = x, y = y))
}

get_t_threshold <- function(a) {
  return(abs(qt(a/2, df = 43)))
}

recode_hot <- function(group) {
  # Flag all significant channels with a>0.1 as *
  group[group > get_t_threshold(0.1)] <- '*'
  return(group)
}

recode_paired_t <- function(group) {
  # Recode t-values so a>0.1, t=*; a>0.5, t=**, a>0.01, t=***
  sig <- matrix(0.1, 128, 1)
  sig[group > get_t_threshold(0.1)] <- 1
  sig[group > get_t_threshold(0.05)] <- 2
  sig[group > get_t_threshold(0.01)] <- 3
  return(sig)
}

recode_groups <- function(paired, group1, group2, levels) {
  # Group as none, both, or subject levels depending on t-test results
  groups <- matrix("none", 128, 1)
  groups[which(paired == group1)] <- levels[1]
  groups[which(paired == group2)] <- levels[2]
  groups[which(group1 == group2)] <- "both"
  groups <- factor(groups, levels = c(levels, "both", "none"))
  return(groups)
}

get_map <- function(paired, group1, group2, levels, layout, title) {
  # Flag significant t-values
  group1_recoded <- recode_hot(abs(group1))
  group2_recoded <- recode_hot(abs(group2))
  paired_recoded <- recode_hot(abs(paired))
  
  # Create data frame for plotting
  groups <- recode_groups(paired_recoded, group1_recoded, group2_recoded, levels)
  
  # Extract significance level of paired-t-test
  # sig <- abs(paired) # Continuous t-values
  sig <- recode_paired_t(abs(paired)) # Discrete signifiance levels instead of t
  
  # Create data frame for plotting
  df <- data.frame(groups = groups, sig = sig, x = layout$x, y = layout$y)
  
  # Create a custom color scale
  myColors <- c("#B8DE29FF", "#287D8EFF", "#29AF7FFF", "#a0a0a0")
  names(myColors) <- levels(df$groups)
  channels <- as.character(1:128)
  
  # Plot
  plot <- ggplot() +
    geom_point(data = df, aes(x = x, y = y, size = sig, color = groups)) +
    
    # Continuous t-values
    # geom_text(data = df, aes(x = x, y = y, label = ifelse(sig > 1.681, channels, " ")), vjust = -1) +
    
    # Discrete significance levels, instead of t
    geom_text(data = df, aes(x = x, y = y, label = ifelse(sig > 0.1, channels, " ")), vjust = -1) +
    
    scale_colour_manual(name = "Group", values = myColors) +
    ggtitle(title) +
    ylim(0, 900) +
    xlim(0, 900) +
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank())
  
  return(plot)
}
```



************

#### 3. Do cortical regions track the levels of each condition differently?

Tested by paired-samples t-tests between the two levels of each condition. I.e. a test of whether an electrode significantly distinguishes condition levels.

``` {r}
# Read files
setwd("/Applications/eeglab2019/talker-change-data-processing/") # Set root dir
xcorr <- load_data("xcorr")
```

```{r}
# One-sample t-tests over each electrode for the same talker condition
t_talker_s <- get_one_sample_t(subset(xcorr, condition = "talker", level = "S"))
t_talker_t <- get_one_sample_t(subset(xcorr, condition = "talker", level = "T"))
t_talker_paired <- get_paired_samples_t(subset(xcorr, condition = "talker", level = "S"),
                                        subset(xcorr, condition = "talker", level = "T"))

# One-sample t-tests over each electrode for the meaning condition
t_meaning_m <- get_one_sample_t(subset(xcorr, condition = "meaning", level = "M"))
t_meaning_n <- get_one_sample_t(subset(xcorr, condition = "meaning", level = "N"))
t_meaning_paired <- get_paired_samples_t(subset(xcorr, condition = "meaning", level = "M"),
                                         subset(xcorr, condition = "meaning", level = "N"))

# One-sample t-tests over each electrode for the high constraint condition
t_constraint_s <- get_one_sample_t(subset(xcorr, condition = "constraint", level = "S"))
t_constraint_g <- get_one_sample_t(subset(xcorr, condition = "constraint", level = "G"))
t_constraint_paired <- get_paired_samples_t(subset(xcorr, condition = "constraint", level = "S"),
                                            subset(xcorr, condition = "constraint", level = "G"))
```

```{r}
layout <- get_layout()
get_map(t_talker_paired, t_talker_t, t_talker_s, c("different", "same"), layout, "Talker")
get_map(t_meaning_paired, t_meaning_m, t_meaning_n, c("meaningful", "nonsense"), layout, "Meaning")
get_map(t_constraint_paired, t_constraint_s, t_constraint_g, c("high constraint", "low constraint"), layout, "Constraint")
```

