---
title: "Lag of maximum cross-correlation values"
author: "Letitia Ho"
date: "10/30/2020"
output: html_document
fig_width: 6
fig_height: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=12, fig.height=2)
library("dplyr")
library("ggplot2")
library("ggpubr")
library("kableExtra")
library("stringr") 
```

```{r load_data, include=FALSE}
setwd("/Users/letitiaho/src/talker_change_data_processing")
original <- read.csv('data/aggregate/lag.csv')
shuffled <- read.csv('data/aggregate/shuffled_lag.csv')
```

```{r}
subset <- function(data, channel, level, shuffle_number = NULL) {
  column_heading <- paste("mean_", channel, sep = "")
  subset <- data[[column_heading]][data$condition == level]
  if (is.null(shuffle_number)) {
    return(data[[column_heading]][data$condition == level])
  } else {
    return(data[[column_heading]][(data$condition == level) & (data$shuffle_number == shuffle_number)])
  }
}

histogram <- function(shuffled_values, original_value, title) {
  ggplot(data.frame(shuffled_values), aes(x = shuffled_values)) +
    geom_histogram(bins = 20) +
    geom_vline(xintercept = original_value, color ='firebrick2', size = 2) +
    ggtitle(title)
}

plot_level <- function(shuffled, original, channel_number, level, title) {
  shuffled_values <- subset(shuffled, channel_number, level)
  original_value <- subset(original, channel_number, level)
  histogram(shuffled_values, original_value, title)
}

plot_channel <- function(shuffled, original, channel_number) {
  same_talker <- plot_level(shuffled, original, channel_number, "S", 
                            paste(channel_number, ": Same Talker", sep = ""))
  different_talker <- plot_level(shuffled, original, channel_number, "T",
                            paste(channel_number, ": Different Talker", sep = ""))
  meaningful <- plot_level(shuffled, original, channel_number, "M",
                            paste(channel_number, ": Meaningful", sep = ""))
  nonsense <- plot_level(shuffled, original, channel_number, "N",
                            paste(channel_number, ": Nonsense", sep = ""))
  low_constraint <- plot_level(shuffled, original, channel_number, "L",
                            paste(channel_number, ": Low constraint", sep = ""))
  high_constraint <- plot_level(shuffled, original, channel_number, "H",
                            paste(channel_number, ": High constraint", sep = ""))
  
  ggarrange(same_talker, different_talker, 
            meaningful, nonsense,
            low_constraint, high_constraint,
            ncol = 6, nrow = 1)
}

proportion <- function(shuffled_values, original_value) {
  if (mean(shuffled_values) > original_value) {
    return(sum(shuffled_values < original_value)/length(shuffled_values))
  } else {
    return(sum(shuffled_values > original_value)/length(shuffled_values))
  }
}

get_proportion <- function(shuffled, original, channel_number, level) {
  shuffled_values <- subset(shuffled, channel_number, level)
  original_value <- subset(original, channel_number, level)
  return(proportion(shuffled_values, original_value))
}

get_channel_proportions <- function(shuffled, original, channel_number) {
  same_talker <- get_proportion(shuffled, original, channel_number, "S")
  different_talker <- get_proportion(shuffled, original, channel_number, "T")
  meaningful <- get_proportion(shuffled, original, channel_number, "M")
  nonsense <- get_proportion(shuffled, original, channel_number, "N")
  low_constraint <- get_proportion(shuffled, original, channel_number, "L")
  high_constraint <- get_proportion(shuffled, original, channel_number, "H")
  return(data.frame("same_talker" = same_talker,
                    "different_talker" = different_talker,
                    "meaningful" = meaningful,
                    "nonsense" = nonsense,
                    "low_constraint" = low_constraint,
                    "high_constraint" = high_constraint))
}
  
get_all_channel_proportions <- function(shuffled, original) {
  all_channel_proportions <- c()
  for (i in 1:128) {
    channel_proportions <- get_channel_proportions(shuffled, original, as.character(i))
    all_channel_proportions <- rbind(all_channel_proportions, channel_proportions)
  }
  return(all_channel_proportions)
}

plot_graded_table <- function(data) {
  data <- mutate_if(data, is.numeric, function(x) {round(x, digits = 7)}) %>%
    mutate_if(is.numeric, function(x) {ifelse(x > 0.1,
                                              cell_spec(x, NULL),
                                              cell_spec(x, background = spec_color(x,
                                                                                   direction = 1,
                                                                                   begin = 0.65,
                                                                                   end = 1,
                                                                                   option = "B",
                                                                                   scale_from = c(0,0.1))))})
  rownames(data) <- c(1:128)
  kable(data, escape = F, row.names = T) %>%
    kable_styling(bootstrap_options = c("hover", "condensed"), full_width = F)
}

convert_to_ms <- function(data, sample_rate = 44100) {
  return(mutate_if(data, is.double, function(x) {-x/(sample_rate/1000)}))
}

```

### Average lag of each channel for each condition


```{r}
get_levels <- function(condition) {
  levels <- list(talker = c("S", "T"), meaning = c("M", "N"), constraint = c("L", "H"))
  return(levels[[condition]])
}

select_data <- function(original, level) {
  return(filter(original, condition == level) %>%
           select(-c("condition", "GroupCount")) %>%
           as.numeric())
  }

combine_data <- function(original, condition) {
  levels <- get_levels(condition)
  data <- data.frame(
    type = c( rep(levels[1], 128), rep(levels[2], 128) ),
    value = c(select_data(original, levels[1]), select_data(original, levels[2]))
  )
  return(data)
}

double_histogram <- function(data, condition) {
  ggplot(data, aes(x=value, fill=type)) +
    geom_histogram(alpha=0.8, position = 'identity', bins = 20) +
    labs(fill="") +
    xlab("ms") +
    ggtitle(str_to_title(condition))
}

plot_double_histogram <- function(original, condition) {
  data <- combine_data(original, condition)
  double_histogram(data, condition)
}
```

**Figure 1**

```{r}
# Convert to miliseconds
shuffled <- convert_to_ms(shuffled)
original <- convert_to_ms(original)

# Create plot for each condition
talker <- plot_double_histogram(original, "talker")
meaning <- plot_double_histogram(original, "meaning")
constraint <- plot_double_histogram(original, "constraint")

# Combine plots into one figure
ggarrange(talker, meaning, constraint, nrow = 1, ncol = 3)
```


### Average lag in observed data in each channel compared to resamplings

**Figure 2**

```{r}
plot_channel(shuffled, original, 1)
plot_channel(shuffled, original, 2)
plot_channel(shuffled, original, 3)
plot_channel(shuffled, original, 30)
```

### Probability of the observed lag 

**Figure 3**

```{r}
all_channel_proportions <- get_all_channel_proportions(shuffled, original)
plot_graded_table(all_channel_proportions)
```


