#!/bin/bash

set -exuo pipefail

# Set up directory in cronusx
ssh cronusx "cd tcdp ; mkdir -p 5_cluster_cross_correlations/figs 5_cluster_cross_correlations/data/logs 5_cluster_cross_correlations/data/distance_scores 5_cluster_cross_correlations/data/weight_scores 5_cluster_cross_correlations/data/cluster_scores"

# Tarball necessary input data files and send to cronusx
tar cJvf tfce_input.tar.xz 5_cluster_cross_correlations/data/weight_scores/weight_scores.RDS 5_cluster_cross_correlations/data/distance_scores/distance_scores.RDS
scp tfce_input.tar.xz cronusx:tcdp

# Extract input files
ssh cronusx "cd tcdp ; tar xJvf tfce_input.tar.xz"

# Run permutations, tail log file
job_id=$(date +%s)
ssh cronusx "cd tcdp ; ./5_cluster_cross_correlations/scripts/run-permutations-for-all-conditions $job_id ; tail -f ./5_cluster_cross_correlations/data/logs/master_${job_id}.log"

# Retrieve output data files and extract
ssh cronusx "cd tcdp ; tar cJvf tfce_output.tar.xz 5_cluster_cross_correlations/data/cluster_scores 5_cluster_cross_correlations/data/logs"
scp cronusx:tcdp/tfce_output.tar.xz .
tar xJvf tfce_output.tar.x
