---
title: "R Notebook"
output: html_notebook
---

```{r setup, warning=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_knit$set(root.dir = "/Users/letitiaho/src/talker_change_data_processing/")
setwd("/Users/letitiaho/src/talker_change_data_processing/")
library("dplyr")
library("ggplot2")
library("ggpubr")
source("tools/functions.R")
source("threshold_free_clustering/src/functions.R")
```

```{r}
coordinates <- get_layout()
# setwd("/Users/letitiaho/src/talker_change_data_processing/")
# getwd()
chan_scores <- readRDS('threshold_free_clustering/data/chan_scores/S.RDS')
df <- data.frame('cluster_scores' = chan_scores, x = coordinates$x, y = coordinates$y, sigmoid_cluster_scores = sigmoid(chan_scores, spread = 6))

plot <- ggplot() +
  geom_point(data = df, aes(x = x, 
                            y = y, 
                            size = sigmoid_cluster_scores, 
                            alpha = 0.5,
                            stroke = 0)) +
  geom_point(data = df, aes(x = x, 
                            y = y, 
                            size = 0.01,
                            alpha = 0.5,
                            stroke = 0)) + 
  scale_size_continuous(name = "p",
                        limits = c(0, 1)) + 
  # labels = c("0.05", "0.01", "0.005") +
  guides(alpha = FALSE) +
  ylim(0, 900) +
  xlim(0, 900) +
  annotate("text", x=20, y=5, label= "L", alpha = 0.8) +
  annotate("text", x=880, y=5, label= "R", alpha = 0.8) +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
plot
ggsave(plot = plot, filename = 'threshold_free_clustering/figs/overall.png', width = 6, height = 5)
```
